/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Chart: typeof import('./components/chart/index.vue')['default']
    GroupPlayIItem: typeof import('./components/GroupPlayIItem.vue')['default']
    GroupPlayItem: typeof import('./components/GroupPlayItem.vue')['default']
    GroupSharingCard: typeof import('./components/GroupSharingCard.vue')['default']
    JoinGroupAvatarList: typeof import('./components/Card/JoinGroupAvatarList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTag: typeof import('vant/es')['Tag']
  }
}
