/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardDescDetail: typeof import('./components/Card/CardDescDetail.vue')['default']
    Chart: typeof import('./components/chart/index.vue')['default']
    GroupPlayItem: typeof import('./components/GroupPlayItem.vue')['default']
    GroupSharingCard: typeof import('./components/GroupSharingCard.vue')['default']
    JoinGroupAvatarList: typeof import('./components/Card/JoinGroupAvatarList.vue')['default']
    OrderItem: typeof import('./components/Order/OrderItem.vue')['default']
    PageView: typeof import('./components/PageView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentInfoForm: typeof import('./components/StudentInfoForm.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanBarrage: typeof import('vant/es')['Barrage']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanForm: typeof import('vant/es')['Form']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
